name: Repository Rebase

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
       - name: Configuring git environment
         run: |
            git config --global user.name RahulPalXDA
            git config --global user.email RahulPal.XDA@gmail.com
            git config --global core.editor nano

       - name: Syncing repo & rebaseing.
         run: |
             git clone https://github.com/ModageOS/android_kernel_xiaomi_sm6125.git -b lineage-18.1-ksu temporary
             cd temporary
             git reset --hard eab6acb610b6d0e176fb2d5605c38312f263a06b

       - name: Pushing commit to repo.
         uses: ad-m/github-push-action@v0.6.0
         with:
           github_token: ${{ secrets.SUPERSECRET }}
           repository: ModageOS/android_kernel_xiaomi_sm6125
           directory: temporary
           branch: lineage-18.1-ksu
           force: true
