name: Repository Rebase

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
       - name: Configuring git environment
         run: |
            git config --global user.name RahulPalXDA
            git config --global user.email RahulPal.XDA@gmail.com
            git config --global core.editor nano

       - name: Syncing repo & rebaseing.
         run: |
             git clone https://github.com/ModageOS/android_frameworks_base.git -b lineage-18.1 temporary
             cd temporary
             git remote rm origin && git remote add origin https://github.com/ModageOS/android_frameworks_base.git
             git fetch origin lineage-18.1-backup
             git cherry-pick 15c84eb12660a81ad4e28a895a9c1d3bdb35683e

       - name: Pushing commit to repo.
         uses: ad-m/github-push-action@v0.6.0
         with:
           github_token: ${{ secrets.SUPERSECRET }}
           repository: ModageOS/android_frameworks_base
           directory: temporary
           branch: lineage-18.1
